### ISSUE TITLE
MacPorts-PHP has failing dependencies

### ISSUE THREAD

**Issue by pdvnl** [sjorek/MacPorts-PHP#1]
--->  Cleaning composer
--->  Computing dependencies for composer-php56
--->  Building composer-php56
Error: Failed to build composer-php56:
Warning: PHP Startup: Unable to load dynamic library '/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gd.so' - dlopen(/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gd.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gdchart.so' - dlopen(/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gdchart.so, 9): image not found in Unknown on line 0
All settings correct for using Composer
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gd.so' - dlopen(/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gd.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gdchart.so' - dlopen(/opt/local/lib/php56/extensions/no-debug-non-zts-20131226/gdchart.so, 9): image not found in Unknown on line 0
Error: See /opt/local/var/macports/logs/_Users_paul_Develop_macports_MacPorts-PHP_php_composer/composer-php56/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port composer-php56 failed

after
`port install php56-gd php56-gdchart`
install succeeds

**Comment by sjorek** [comment]
Sorry for being busy quite a while and answering late …

This issue is not reproducible for me. I guess you had two dangling configuration files, like `/opt/local/var/db/php56/gd.ini` and `/opt/local/var/db/php56/gdchart.ini` which tried to load these extensions, although they were not installed anymore. Hence your report does not have anything to do with this port …

I'll close this issue. If you still encounter any trouble, open a new issue or add a comment here.

**Comment by pdvnl** [comment]
> On 07 Feb 2018, at 11:21, Stephan Jorek <notifications@github.com> wrote:
> 
> Sorry for being busy quite a while and answering late …
> 
> This issue is not reproducible for me. I guess you had two dangling configuration files, like /opt/local/var/db/php56/gd.ini and /opt/local/var/db/php56/gdchart.ini which tried to load these extensions, although they were not installed anymore. Hence your report does not have anything to do with this port …
> 
> I'll close this issue. If you still encounter any trouble, open a new issue or add a comment here.
> 
you are right. after removing botg .ini's install went fine.

thank you,
paul.
