### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by alexkuc** [sjorek/macports-php#21]
According to MacPorts doc for [local portfile repositories](https://guide.macports.org/chunked/development.local-repositories.html):

> The file URL should always appear before the rsync URL so that local Portfiles can be tested that are duplicated in the MacPorts tree, because port will always operate on the first Portfile it encounters.

However, in the current instructions (in this repository), the `file:///...` is added at the end of the `sources.conf` file:

```bash
$ sudo bash -c "cat <<EOF >>/opt/local/etc/macports/sources.conf

file://${PWD} [nosync]

EOF"
```

Should the installation instructions be updated with this info from the manpage?

**Comment by brandung-sjorek** [comment]
@alexkuc Installation instructions have been updated, I'll close this issue now …
