### ISSUE TITLE
Checksum (rmd160) mismatch for installer

### ISSUE THREAD

**Issue by drugurkocak** [sjorek/macports-php#3]
Hi, 
I am trying to install composer-php72 and its dependencies on my macport MAMP installation. It includes mysql57 @5.7.17 , php72 @7.2.13, apache  @2.4.37.
I get an checksum mismatch error. I need to test installing OJS 3 (open journal system) on my local server, and then install it via github on web.
Can you help me?
Log file is attached,
Best Regards,
Ugur

[main.log](https://github.com/sjorek/macports-php/files/2752662/main.log)

**Comment by brandung-sjorek** [comment]
Should be fixed in my own fork: https://github.com/brandung-sjorek/macports-php … 

Sorry for the late reply.
Cheers!

**Comment by sjorek** [comment]
The fork has been merged into this repo …
