### ISSUE TITLE
Selecting 'composer2-php80' for 'composer' failed: The specified version 'composer2-php80' is not valid.

### ISSUE THREAD

**Issue by onodera-punpun** [sjorek/macports-php#39]
Getting this error on `sudo port select composer composer2-php80`, though composer2-php IS installed...

**Comment by brandung-sjorek** [comment]
@onodera-punpun Which error do you get? 

Hint: If you want to select `composer2-php80` as you default composer, you'll have to install `composer2-php80` (and not `composer2-php` as you stated)

**Comment by brandung-sjorek** [comment]
@onodera-punpun My last comment was nonsense. Your description was not very precise. Nevertheless, I could find a tiny glitch in teh composer-selection configuration. So, please sync this repository with the latest upstream, upgrade all outdated composer-ports and the issue should be solved. 

I appreciate any feedback regarding this issue!

**Comment by brandung-sjorek** [comment]
Closing due to lack of feedback …
